apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd-63-ibm-connect-direct-serviceaccount
  labels:
    app.kubernetes.io/name: ibm-connect-direct
    app.kubernetes.io/instance: cd-63
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: ibm-connect-direct-1.3.0
    release: cd-63
imagePullSecrets:
  - name: ibm-entitlement-key