apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cd-62-ibm-connect-direct-podclusterrole
  labels:
    app.kubernetes.io/name: ibm-connect-direct
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list