apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: ibm-connect-direct-psp
  labels:
    app: "ibm-connect-direct-psp"
spec:
  privileged: false
  allowPrivilegeEscalation: true
  hostPID: false
  hostIPC: false
  hostNetwork: false
  requiredDropCapabilities:
  allowedCapabilities:
  - CHOWN
  - FOWNER
  - SETGID
  - SETUID
  - DAC_OVERRIDE
  - AUDIT_WRITE
  - SYS_CHROOT
  allowedHostPaths:
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 4294967294
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 4294967294
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 4294967294
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - nfs
  - persistentVolumeClaim
  - projected
  - secret
  forbiddenSysctls:
  - '*'
